server:
    port: 8080
#logging.file: driftavbrott_rest.log
endpoints.health.enabled: true
security.basic.enabled: false
management.security.enabled: false

spring.data.mongodb.uri: mongodb://mongo:27000/driftavbrott
